name: bookaround
description: Un'app per l'interscambio di libri - scolastici e non.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Grafica
  # cupertino_icons: ^1.0.2
  code_field: ^1.22.0
  google_fonts: ^1.1.2

  # Firebase
  cloud_firestore: ^0.16.0
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  cloud_functions: ^0.9.0

  # Logica
  provider: ^4.3.3
  rxdart: ^0.25.0

  # Modelli
  json_annotation: ^3.1.1

  # Utilità
  form_field_validator: ^1.0.1
  cached_network_image: ^2.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter pub run build_runner build --delete-conflicting-outputs
  json_serializable: ^3.5.1
  build_runner: ^1.11.0


flutter:
  uses-material-design: true


flutter_intl:
  enabled: true