name: bookaround
description: Un'app per l'interscambio di libri - scolastici e non.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 0.1.0+22


environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Grafica
  # cupertino_icons: ^1.0.2
  code_field:
    git: https://github.com/emiliodallatorre/code_field.git
  google_fonts: ^2.0.0
  showcaseview: ^1.0.0

  # Firebase
  cloud_firestore: ^1.0.6
  firebase_auth: ^1.1.1
  firebase_core: ^1.0.4
  cloud_functions: ^1.0.4
  firebase_messaging: ^9.1.2
  firebase_storage: ^8.0.4
  firebase_crashlytics: ^2.0.1
  firebase_dynamic_links: ^2.0.1

  # Logica
  provider: ^5.0.0
  rxdart: ^0.26.0

  # Modelli
  json_annotation: ^4.0.1

  # Utilità
  form_field_validator: ^1.1.0
  cached_network_image: ^3.0.0
  flutter_barcode_scanner: ^2.0.0-nullsafety.0
  random_string: ^2.2.0-nullsafety
  shared_preferences: ^2.0.5
  timeago: ^3.0.2
  overlay_support: ^1.2.1

  # Localizzazione
  flutter_google_places_hoc081098: ^1.0.0-nullsafety.1
  google_maps_webservice: ^0.0.19
  # geoflutterfire:
  #   git:
  #     url: git://github.com/emiliodallatorre/GeoFlutterFire.git
  #     ref: update_deps
  geoflutterfire: ^3.0.0-nullsafety.1
  flutter_geocoder: ^0.2.2-nullsafety
  geolocator: ^7.0.3
  google_maps_flutter: ^2.0.3
  location: ^4.1.1

  # File
  image_picker: ^0.7.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter pub run build_runner build --delete-conflicting-outputs
  json_serializable: ^4.1.0
  build_runner: ^1.12.2

  # flutter pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.9.0

  # flutter pub run r_flutter:generate
  r_flutter: ^0.7.1


flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf


flutter_intl:
  enabled: true


flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/ic_launcher_white.png"
  image_path_android: "assets/ic_launcher_android.png"
